connector_type: kafka
bootstrap_server: "redpanda:9092"
topic: nba_live
consumer_group: nba_events
include_metadata: true         # CAMBIO: Un DE siempre quiere metadatos (offset, timestamp)
api_version: "2.8.0"
auto_offset_reset: earliest    # O 'latest' si no te importan los datos históricos al reiniciar
batch_size: 5               # CAMBIO: Un poco más alto para eficiencia en ráfagas
timeout_ms: 100                # CAMBIO: Latencia sub-segundo para que sea "Live"

# Uncomment the config below to use SSL config
# security_protocol: "SSL"
# ssl_config:
#   cafile: "CARoot.pem"
#   certfile: "certificate.pem"
#   keyfile: "key.pem"
#   password: password
#   check_hostname: true

# Uncomment the config below to use SASL_SSL config
# security_protocol: "SASL_SSL"
# sasl_config:
#   mechanism: "PLAIN"
#   username: username
#   password: password

# Uncomment the config below to use protobuf schema to deserialize message
# serde_config:
#   serialization_method: PROTOBUF
#   schema_classpath: "path.to.schema.SchemaClass"
